In [5]:
#pip install opencv-python

In [25]:
import numpy as np
import cv2

- Usando seus conhecimentos em Python, faça uma matriz (20x20) com as duas diagonais marcadas com o número 255 e as demais com 0;
- Em seguida, salve a matriz como uma imagem, usando a LIB opencv.


In [26]:
import numpy as np
tam = 18
# Criando uma matriz 20x20 com valores 0
matrix = np.zeros((tam,tam), dtype=np.uint8)

# Preenchendo as duas diagonais com o valor 255
for i in range(tam):
    matrix[i,i] = 255
    matrix[i,(tam-1)-i] = 255

# Imprimindo a matriz resultante
print(matrix)


[[255   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 255]
 [  0 255   0   0   0   0   0   0   0   0   0   0   0   0   0   0 255   0]
 [  0   0 255   0   0   0   0   0   0   0   0   0   0   0   0 255   0   0]
 [  0   0   0 255   0   0   0   0   0   0   0   0   0   0 255   0   0   0]
 [  0   0   0   0 255   0   0   0   0   0   0   0   0 255   0   0   0   0]
 [  0   0   0   0   0 255   0   0   0   0   0   0 255   0   0   0   0   0]
 [  0   0   0   0   0   0 255   0   0   0   0 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255   0   0 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255   0   0 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255   0   0   0   0 255   0   0   0   0   0   0]
 [  0   0   0   0   0 255   0   0   0   0   0   0 255   0   0   0   0   0]
 [  0   0   0   0 255   0

In [27]:
import cv2
cv2.imwrite("diagonal_matrix.png", matrix)

True

# Atividade 2 CNN

In [49]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
# carrega o conjunto de dados MNIST
mnist = tf.keras.datasets.mnist

# Ler os dados jã normalizados 
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_data = np.concatenate((x_train, x_test), axis=0)
y_data = np.concatenate((y_train, y_test), axis=0)


In [50]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=42)

In [43]:
def imprimir_matriz(matriz):
    for linha in matriz:
        for elemento in linha:
            print(f"{elemento:4}", end="")  # Define a largura do elemento como 4
        print()  # Pula para a próxima linha após imprimir uma linha completa

imprimir_matriz(x_train[20])

   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  38 190  25   0   0   0   0   0   0   0   0
   0   0   0  13  25  10   0   0   0   0   0   0   0   0   0   0   0 112 252 125   4   0   0   0   0   0   0   0
   0   0   0 132 252 113   0   0   0   0   0   0   0   0   0   0   0  61 252 252  36   0   0   0   0   0   0   0
   0   0   0 132 252 240  79   0   0   0   0   0   0   0   0   0   0  84 252 252  36   0   0   0   0   0   0   0
   0   0   0 132 252 252 238  52   0   0   0   0   0   0   0   0  12 198 252 252 122   0   0   0

In [51]:
y_train

array([0, 4, 4, ..., 1, 0, 0], dtype=uint8)

In [45]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten

model = Sequential()
model.add(Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(28,28,1)))
model.add(Conv2D(64, kernel_size=(3,3), activation='relu'))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))


In [46]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [47]:
from keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

model.fit(X_train, y_train, batch_size=128, epochs=10, verbose=1)


Epoch 1/10


2023-06-13 21:46:21.751686: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


383/383 [==============================] - 9s 22ms/step - loss: 0.9117 - accuracy: 0.9360
Epoch 2/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0503 - accuracy: 0.9846
Epoch 3/10
383/383 [==============================] - 8s 20ms/step - loss: 0.0317 - accuracy: 0.9894
Epoch 4/10
383/383 [==============================] - 8s 20ms/step - loss: 0.0195 - accuracy: 0.9934
Epoch 5/10
383/383 [==============================] - 8s 20ms/step - loss: 0.0197 - accuracy: 0.9935
Epoch 6/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0171 - accuracy: 0.9941
Epoch 7/10
383/383 [==============================] - 8s 20ms/step - loss: 0.0128 - accuracy: 0.9958
Epoch 8/10
383/383 [==============================] - 8s 20ms/step - loss: 0.0129 - accuracy: 0.9955
Epoch 9/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0153 - accuracy: 0.9952
Epoch 10/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0159 - accuracy: 0.9951


In [10]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)
y_test = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1-score:', f1)


 29/657 [>.............................] - ETA: 3s

2023-06-13 13:57:35.930875: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


657/657 [==============================] - 4s 6ms/step
Accuracy: 0.9783809523809524
Precision: 0.9783094519175635
Recall: 0.9782094718779124
F1-score: 0.9782427899488854


In [ ]:
model.predict(img_nova)

In [11]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
# carrega o conjunto de dados MNIST
mnist = tf.keras.datasets.mnist
# Ler os dados jã normalizados 
(x_train, y_train), (x_test, y_test) = mnist.load_data()

5


In [23]:
print(y_train[0])

5


In [24]:
import plotly.express as px
fig = px.imshow(matrix)
fig.show()

In [21]:
fig = px.imshow(x_train[2])
fig.show()

In [22]:
import plotly.graph_objects as go

import pandas as pd


fig = go.Figure(data=[go.Surface(z=x_train[0])])

fig.update_layout(title='Numero', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()