In [1]:
import plotly.express as px
import numpy as np
import numpy as np
import cv2
img_rgb = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                    [[0, 255, 0], [0, 0, 255], [255, 0, 0]]
                   ], dtype=np.uint8)
fig = px.imshow(img_rgb)
fig.show()

In [2]:
import numpy as np
tam = 18
# Criando uma matriz 20x20 com valores 0
matrix = np.zeros((tam,tam), dtype=np.uint8)

# Preenchendo as duas diagonais com o valor 255
for i in range(tam):
    matrix[i,i] = 255
    matrix[i,(tam-1)-i] = 255

# Imprimindo a matriz resultante
print(matrix)


[[255   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 255]
 [  0 255   0   0   0   0   0   0   0   0   0   0   0   0   0   0 255   0]
 [  0   0 255   0   0   0   0   0   0   0   0   0   0   0   0 255   0   0]
 [  0   0   0 255   0   0   0   0   0   0   0   0   0   0 255   0   0   0]
 [  0   0   0   0 255   0   0   0   0   0   0   0   0 255   0   0   0   0]
 [  0   0   0   0   0 255   0   0   0   0   0   0 255   0   0   0   0   0]
 [  0   0   0   0   0   0 255   0   0   0   0 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255   0   0 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255   0   0 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255   0   0   0   0 255   0   0   0   0   0   0]
 [  0   0   0   0   0 255   0   0   0   0   0   0 255   0   0   0   0   0]
 [  0   0   0   0 255   0

In [4]:
import plotly.express as px
fig = px.imshow(matrix)
fig.show()

# Mnist

In [3]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
# carrega o conjunto de dados MNIST
mnist = tf.keras.datasets.mnist

# Ler os dados jã normalizados 
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_data = np.concatenate((x_train, x_test), axis=0)
y_data = np.concatenate((y_train, y_test), axis=0)


In [21]:
def imprimir_matriz(matriz):
    for linha in matriz:
        for elemento in linha:
            print(f"{elemento:4}", end="")  # Define a largura do elemento como 4
        print()  # Pula para a próxima linha após imprimir uma linha completa

img_index = 3
imprimir_matriz(x_train[img_index])
print(y_train[img_index])


   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 124 253 255  63   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  96 244 251 253  62   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 127 251 251 253  62   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  68 236 251 211  31   8   0   0

In [17]:
img_index = 0
fig = px.imshow(x_train[img_index])
fig.show()

In [18]:
import plotly.graph_objects as go
import pandas as pd


fig = go.Figure(data=[go.Surface(z=x_train[0])])

fig.update_layout(title='Numero', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()