In [58]:
import numpy as np
import pandas as pd
import cv2


In [63]:
matriz = np.zeros((20,20),dtype=int)
print(matriz)
type(matriz)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


numpy.ndarray

In [60]:
np.fill_diagonal(matriz,255) #preenche a diagonal principal
np.fill_diagonal(np.fliplr(matriz), 255) #espelho a matriz e preencho a diagnoal principal novamente

In [61]:
#print(matriz)

new_matriz = pd.DataFrame(matriz)

print(new_matriz)

     0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0   255    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
1     0  255    0    0    0    0    0    0    0    0    0    0    0    0    0   
2     0    0  255    0    0    0    0    0    0    0    0    0    0    0    0   
3     0    0    0  255    0    0    0    0    0    0    0    0    0    0    0   
4     0    0    0    0  255    0    0    0    0    0    0    0    0    0    0   
5     0    0    0    0    0  255    0    0    0    0    0    0    0    0  255   
6     0    0    0    0    0    0  255    0    0    0    0    0    0  255    0   
7     0    0    0    0    0    0    0  255    0    0    0    0  255    0    0   
8     0    0    0    0    0    0    0    0  255    0    0  255    0    0    0   
9     0    0    0    0    0    0    0    0    0  255  255    0    0    0    0   
10    0    0    0    0    0    0    0    0    0  255  255    0    0    0    0   
11    0    0    0    0    0 

In [62]:
cv2.imwrite('matriz_artur.png',matriz)

True