In [1]:
import numpy as np

In [ ]:
matriz = (20,20)

In [4]:
matriz = np.zeros((20,20),dtype=int)
print(matriz)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [8]:
for i in range(20):
    matriz[i,i]=255

    

In [16]:
for j in range(20):
    matriz[j,-j]= 255

In [18]:
print(matriz)

[[255   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0 255   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0 255]
 [  0   0 255   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  255   0]
 [  0   0   0 255   0   0   0   0   0   0   0   0   0   0   0   0   0 255
    0   0]
 [  0   0   0   0 255   0   0   0   0   0   0   0   0   0   0   0 255   0
    0   0]
 [  0   0   0   0   0 255   0   0   0   0   0   0   0   0   0 255   0   0
    0   0]
 [  0   0   0   0   0   0 255   0   0   0   0   0   0   0 255   0   0   0
    0   0]
 [  0   0   0   0   0   0   0 255   0   0   0   0   0 255   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0 255   0   0   0 255   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0 255   0 255   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0   0 255   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0   0   0   0 255   0 255   0   0   0   0

In [20]:
pip install opencv-python

     ---------------------------------------- 38.2/38.2 MB 9.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [21]:
import cv2
cv2.imwrite("diagonal_matrix.png",matriz)

True