In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import pandas as pd
import unicodedata
import re
import numpy as np

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df= pd.read_csv('https://raw.githubusercontent.com/natorjunior/debates-ideologicos/main/dataset.csv')

In [3]:
df.head()

Text  Label
0  diego freitas e a jovem pobre q mora no morro ...      1
1  moral e algo pessoal não tente enfiar seus val...      1
2  eu acho engraçado que se posicionar sobre o út...      1
3  adriano barboza da mesma forma como vc demonst...      1
4  a vida termina qnd acaba atividade cerebral en...      1

In [7]:
X = df.iloc[:,0]


In [9]:
y = df.iloc[:,1] 

In [15]:
vectorizer = CountVectorizer()# criando uma instância do vetorizador BoW
bow_matrix = vectorizer.fit_transform(X)# criando a matriz BoW

In [17]:
# exibindo o vocabulário criado pelo vetorizador
print(vectorizer.vocabulary_)


{'diego': 2321, 'freitas': 3463, 'jovem': 4204, 'pobre': 5692, 'mora': 4815, 'no': 5052, 'morro': 4843, 'sem': 6773, 'instrução': 4055, 'criança': 1789, 'vai': 7477, 'nascer': 4956, 'viver': 7640, 'em': 2601, 'pessimas': 5628, 'condições': 1513, 'cair': 1032, 'na': 4935, 'criminalidade': 1801, 'facil': 3145, 'falar': 3163, 'sobre': 6913, 'proibição': 6046, 'do': 2460, 'aborto': 68, 'qundo': 6266, 'se': 6737, 'homem': 3735, 'de': 1943, 'classe': 1296, 'media': 4639, 'moral': 4819, 'algo': 347, 'pessoal': 5631, 'não': 5102, 'tente': 7158, 'enfiar': 2656, 'seus': 6847, 'valores': 7490, 'morais': 4818, 'outra': 5273, 'pessoa': 5629, 'isso': 4164, 'existe': 3079, 'sou': 6980, 'favor': 3229, 'da': 1911, 'legalização': 4332, 'uma': 7411, 'escolha': 2800, 'mulher': 4904, 'afinal': 263, 'quem': 6230, 'paga': 5298, 'pato': 5429, 'depois': 2099, 'somos': 6973, 'nós': 5105, 'mesmas': 4715, 'quer': 6232, 'abortar': 49, 'sendo': 6784, 'legal': 4318, 'ou': 5270, 'fazer': 3243, 'vocêa': 7657, 'acham':

In [18]:
# exibindo a matriz BoW
print(bow_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
 X_train, X_test, y_train, y_test = train_test_split(bow_matrix.toarray(), y, test_size=0.30, random_state=42)

In [20]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification

In [23]:
clf = MLPClassifier(random_state=1, max_iter=100).fit(X_train, y_train)

In [24]:
y_pred = clf.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [26]:
ac = accuracy_score(y_test, y_pred)

In [35]:
f1 = f1_score(y_test, y_pred, average='weighted')

In [29]:
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [36]:
re = recall_score(y_test, y_pred, average='weighted')
prec = precision_score(y_test, y_pred, average='weighted')

In [37]:
print(f'acuracia: {ac}')
print(f'f1: {f1}')
print(f'precision score: {prec}')
print(f'recall score: {re}')

acuracia: 0.8210922787193974
f1: 0.8193470098485263
precision score: 0.8226874665543993
recall score: 0.8210922787193974
